// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwfkilwlnkoaabcnqyfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3ZmtpbHdsbmtvYWFiY25xeWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODUyNDAsImV4cCI6MjA1ODk2MTI0MH0.O2cHkuh0E0tiB9Vm4XMhQEDwUaXuQJ9zUmJUe3xJZp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);